# Course 1 - The Data Scientist's Toolbox:
## Quiz 3:
### Question 1

We take a random sample of individuals in a population and identify whether they smoke and if they have cancer. We observe that there is a strong relationship between whether a person in the sample smoked or not and whether they have lung cancer. We claim that the smoking is related to lung cancer in the larger population. We explain we think that the reason for this relationship is because cigarette smoke contains known carcinogens such as arsenic and benzene, which make cells in the lungs become cancerous.

**Answer**

- This is an example of an inferential data analysis.

### Question 2

What is the most important thing in Data Science?

**Answer**

- The question you are trying to answer.

### Question 3:

If the goal of a study was to relate Martha Stewart Living Subscribers to Our Site's Users based on the number of people that lived in each region of the US, what would be the potential problem? 

(http://xkcd.com/1138/)

**Answer**

- There would be confounding because the number of people that live in an area is related to both Martha Stewart Living Subscribers and Our Site's Users.

### Question 4:

What is an experimental design tool that can be used to address variables that may be confounders at the design phase of an experiment?

**Answer**

- Stratifying variables.

**Explanation**

From wikipedia:
"In statistics, stratified sampling is a method of sampling from a population.


In statistical surveys, when subpopulations within an overall population vary, it is advantageous to sample each subpopulation (stratum) independently. Stratification is the process of dividing members of the population into homogeneous subgroups before sampling. The strata should be mutually exclusive: every element in the population must be assigned to only one stratum. The strata should also be collectively exhaustive: no population element can be excluded. Then simple random sampling or systematic sampling is applied within each stratum. This often improves the representativeness of the sample by reducing sampling error. It can produce a weighted mean that has less variability than the arithmetic mean of a simple random sample of the population.

In computational statistics, stratified sampling is a method of variance reduction when Monte Carlo methods are used to estimate population statistics from a known population."

### Question 5

What is the reason behind the explosion of interest in big data?

**Answers**

- The price and difficulty of collecting and storing data has dramatically dropped.
