# Quiz 2

## Question 1

Who created Markdown?

- Yihui Xie             [x]
- Robert Gentleman      [x]
- Hadley Wickham        [x]
- John Gruber           [v]

## Question 2

When writing a document in R Markdown, how do you denote the beginning of an R code chunk?

- \<code\>                [x]
- \<rcode\>               [x]
- ```                   [x]
- ```\{r\}                [V]

## Question 3

When using knitr, how do you indicate the height and width of a plot created in a code chunk?

- Set the 'dpi' option for the code chunk                               [x]
- Set the 'height' and 'width' options for the code chunk               [x]
- Set the 'fig.height' and 'fig.width' options for the code chunk       [v]
- Set the 'size' and 'scale' options for the code chunk                 [x]

## Question 4

With some code chunks, we may not want the output generated by the chunk to be rendered into HTML but would prefer to print the output verbatim. How can we specify this preference for a given code chunk?

- Set the option message=FALSE          [x]
- Set the option results="asis"         [v]
- Set the option tidy=FALSE             [x]
- Set the option highlight=TRUE         [x]

## Question 5

When using knitr and R Markdown and producing output in HTML, why should you never edit the resulting HTML file?

- The HTML file is not a text file.     [x]
- Every time you knit() the R Markdown file, the HTML file will be overwritten                             [v]
- Editing the HTML file requires knowledge of a separate markup language.               [x]
- The Markdown file generated by knitr is the appropriate file to edit. [x]